### ISSUE TITLE
[Bug] AttributeError: 'ConfigDict' object has no attribute 'data_preprocessor' when convert mobilenetV2 to ONNX

### ISSUE THREAD

**Issue by biyuehuang** [open-mmlab/mmpretrain#1549]
### Branch

main branch (mmpretrain version)

### Describe the bug

model download from https://github.com/open-mmlab/mmpretrain/tree/main/configs/mobilenet_v2

when convert mobilenetV2 to ONNX, Error exist.

$ python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmdet/detection/detection_onnxruntime_dynamic.py \
    mmpretrain/configs/mobilenet_v2/mobilenet-v2_8xb32_in1k.py \
    mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth \
    mmdetection/demo/demo.jpg \
    --work-dir mobilenetv2/ \
    --device cpu \
    --dump-info

05/06 17:44:07 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
05/06 17:44:07 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
05/06 17:44:07 - mmengine - WARNING - Failed to import `None.registry` make sure the registry.py exists in `None` package.
05/06 17:44:07 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
/home/a380/Downloads/kiwi/MTL/mmdetection/mmdet/utils/setup_env.py:111: UserWarning: The current default scope "mmpretrain" is not "mmdet", `register_all_modules` will force the currentdefault scope to be "mmdet". If this is not expected, please set `init_default_scope=False`.
  warnings.warn('The current default scope '
Traceback (most recent call last):
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmengine/config/config.py", line 52, in __getattr__
    value = super().__getattr__(name)
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/addict/addict.py", line 67, in __getattr__
    return self.__getitem__(item)
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmengine/config/config.py", line 48, in __missing__
    raise KeyError(name)
KeyError: 'data_preprocessor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mmdeploy/tools/deploy.py", line 335, in <module>
    main()
  File "mmdeploy/tools/deploy.py", line 129, in main
    export2SDK(
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/sdk/export_info.py", line 348, in export2SDK
    pipeline_info = get_pipeline(deploy_cfg, model_cfg, work_dir, device)
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/sdk/export_info.py", line 281, in get_pipeline
    preprocess = get_preprocess(deploy_cfg, model_cfg, device=device)
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/sdk/export_info.py", line 197, in get_preprocess
    transforms = task_processor.get_preprocess()
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 283, in get_preprocess
    data_preprocessor = model_cfg.model.data_preprocessor
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmengine/config/config.py", line 54, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'ConfigDict' object has no attribute 'data_preprocessor'

### Environment

refer to https://github.com/open-mmlab/mmdeploy/blob/main/docs/zh_cn/get_started.md 
I can execute this command sucessfully
python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmdet/detection/detection_onnxruntime_dynamic.py \
    mmdetection/configs/faster_rcnn/faster-rcnn_r50_fpn_1x_coco.py \
    checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    mmdetection/demo/demo.jpg \
    --work-dir mobilenetv2/faster-rc \
    --device cpu \
    --dump-info

**Comment by RunningLeon** [comment]
@biyuehuang hi, it seems you are using the wrong deploy config `mmdeploy/configs/mmdet/detection/detection_onnxruntime_dynamic.py`, pls. try with [configs/mmpretrain/classification_onnxruntime_dynamic.py](https://github.com/open-mmlab/mmdeploy/blob/main/configs/mmpretrain/classification_onnxruntime_dynamic.py)

**Comment by biyuehuang** [comment]
@RunningLeon 
New error exist.
$ python mmdeploy/tools/deploy.py     mmdeploy/configs/mmpretrain/classification_onnxruntime_dynamic.py     mmpretrain/configs/mobilenet_v2/mobilenet-v2_8xb32_in1k.py     mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth     mmdetection/demo/demo.jpg     --work-dir model_onnx/mobilenetv2/     --device cpu     --dump-info
05/08 10:50:51 - mmengine - WARNING - Failed to get codebase, got: 'Cannot get key by value "mmpretrain" of <enum \'Codebase\'>'. Then export a new codebase in Codebase MMPRETRAIN: mmpretrain
05/08 10:50:51 - mmengine - WARNING - Import mmdeploy.codebase.mmpretrain.deploy failedPlease check whether the module is the custom module.No module named 'mmdeploy.codebase.mmpretrain'
Traceback (most recent call last):
  File "mmdeploy/tools/deploy.py", line 335, in <module>
    main()
  File "mmdeploy/tools/deploy.py", line 129, in main
    export2SDK(
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/sdk/export_info.py", line 347, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/sdk/export_info.py", line 262, in get_deploy
    _, customs = get_model_name_customs(
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/sdk/export_info.py", line 61, in get_model_name_customs
    task_processor = build_task_processor(
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/utils/utils.py", line 46, in build_task_processor
    import_codebase(codebase_type, custom_module_list)
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/codebase/__init__.py", line 35, in import_codebase
    codebase = get_codebase_class(codebase_type)
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/codebase/base/mmcodebase.py", line 86, in get_codebase_class
    return CODEBASE.build({'type': codebase.value})
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'mmpretrain is not in the Codebases registry. Please check whether the value of `mmpretrain` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by RunningLeon** [comment]
@biyuehuang pls. try latest `main` branch from mmdeploy

**Comment by biyuehuang** [comment]
> @biyuehuang pls. try latest `main` branch from mmdeploy

Thx @RunningLeon 
I can export ONNX model successfully refer to 
https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/01-how-to-build/linux-x86_64.md

python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmpretrain/classification_onnxruntime_dynamic.py \
    mmpretrain/configs/mobilenet_v2/mobilenet-v2_8xb32_in1k.py \
    mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth \
    mmdetection/demo/demo.jpg \
    --work-dir model_onnx/mobilenetv2/ \
    --device cpu \
    --dump-info
