### ISSUE TITLE
[Feature] implement SimCLR or DenseCL self-supervised approach on a backbone of HRNet

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmpretrain#1557]
### Describe the feature

I would like to use the approach of self-supervised learning on a model based on HRnet w32 . 

I noticed through the document that both simclr and densecl are based on ResNet 50
is that possible ? and how can i do so ?

could you please guide me. as i try to make it with inherit the head and neck of simclr model and add the backbone of HRnet-w32 but it gives me this error message : 

`  File "/scratch/shubbak/mmpretrain/mmpretrain/models/necks/nonlinear_neck.py", line 101, in forward
    assert len(x) == 1
AssertionError`

<img width="853" alt="image" src="https://github.com/open-mmlab/mmpretrain/assets/10245810/1ec571c9-cde4-4ce3-8bc3-a5ebffe19ec1">

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by fangyixiao18** [comment]
I'll try it ASAP to check the error

**Comment by guneetmutreja** [comment]
I can give a temporary fix but @fangyixiao18 can correct me if I am wrong and provide a better solution.

That's because HRNet backbone returns a 4 stage output, passing one of those in a tuple format from the SimCLR.py will resolve the issue.
Edit the line in loss function in the SimCLR.py file to: 
z = self.neck([x[3]])[0]  # you can decide on which stage output you want to pass to the neck, here I am passing last stage output

Also, accordingly correct the in_channels and hid_channels arguments of the neck in the config file. It can be 18, 36, 72 or 144 for stage 0, 1, 2, and 3 respectively.

**Comment by alaa-shubbak** [comment]
> I can give a temporary fix but @fangyixiao18 can correct me if I am wrong and provide a better solution.
> 
> That's because HRNet backbone returns a 4 stage output, passing one of those in a tuple format from the SimCLR.py will resolve the issue. Edit the line in loss function in the SimCLR.py file to: z = self.neck([x[3]])[0] # you can decide on which stage output you want to pass to the neck, here I am passing last stage output
> 
> Also, accordingly correct the in_channels and hid_channels arguments of the neck in the config file. It can be 18, 36, 72 or 144 for stage 0, 1, 2, and 3 respectively.

Thank you very much. I will try your suggestion. 
what about the connection between HRnet and the denseclr neck ?

the normal densecl neck is DenseCLNeck

```
dict(type='DenseCLNeck',# densecl neck
        in_channels=2048,
        hid_channels=2048,
        out_channels=128,
        num_grid=None)

```

while the normal neck of HRNet-w32 is consist of two parts as bellow 

```
 neck=[
        dict(type='HRFuseScales', in_channels=(32, 64, 128, 256)),
        dict(type='GlobalAveragePooling'),
    ],
```

how can i connect the denseCL  neck with HRnet?

**Comment by fangyixiao18** [comment]
sorry for the late reply. you could add `DenseCLNeck` to the list of HRNet-w32 neck, but we didn't this before, I am not sure about the correctness of the forward pass, you may need to check the dimension by yourself

**Comment by alaa-shubbak** [comment]
after update the model as you mentioned i got this error
`
ValueError: Input dimension should be at least 3`
which was similar to previous error when implement the HRnet with simclr neck and head. 

after writing a statement to print the size of output from GlobalAvragePooling in the new neck . it gives me that 

```
    print('the output of average global layer is', torch.Size(outs))
TypeError: torch.Size() takes an iterable of 'int' (item 0 is 'Tensor')

```
so it seems to me that the neck should not have the GlobalAveragePooling between the HRfuseScale layer and the DenseCLNeck layer. 
we shall have something else . 

I try the model without average pooling layer , but it gives error as bellow

`the size of output of hrnet fuse neck torch.Size([32, 2048, 7, 7])
Traceback (most recent call last):
  File "tools/train.py", line 160, in <module>
    main()
  File "tools/train.py", line 156, in main
    runner.train()
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1721, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/runner/loops.py", line 97, in run
    self.run_epoch()
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/runner/loops.py", line 116, in run_epoch
    self.run_iter(idx, data_batch)
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/runner/loops.py", line 134, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/shubbak/mmpretrain/mmpretrain/models/selfsup/base.py", line 127, in forward
    return self.loss(inputs, data_samples)
  File "/scratch/shubbak/mmpretrain/mmpretrain/models/selfsup/densecl.py", line 182, in loss
    densecl_sim_q = (q_grid * indexed_k_grid).sum(1)  # NxS^2
RuntimeError: The size of tensor a (49) must match the size of tensor b (3136) at non-singleton dimension 2
 `
as i understand the output tensor from HRFuseSacle layer is ([32, 2048, 7, 7])
and the error   is 
`
The size of tensor a (49) must match the size of tensor b (3136) at non-singleton dimension 2
`

actually , i don't know the meaning of those numbers and from where they come. 
and i don't know what types of layer shall i integrate between the HRFuseScales and DenseCLNeck layer?

**Comment by fangyixiao18** [comment]
it is because the implementation of the densecl algorithms, you could set breakpoint before the position that the log mentioned to check the dimenstion.

**Comment by alaa-shubbak** [comment]
hello , thanks for your suggestions.

the output from the HRfuseScale layer is [32, 2048, 7, 7]
the desecl neck layer has in_channel = 2048 ,which is compatable with the output of previous layer (HRFuseScale ) 

I am wondering if i shall keep the GlobalAveragePooling layer between the densecl neck and the HRFuse scales neck. 
even more , the inner of the densecl neck contains the AdaptiveAvgPool2d 
what do you think ? 

> it is because the implementation of the densecl algorithms, you could set breakpoint before the position that the log mentioned to check the dimenstion.

I got where was the error . the densecl model has matric multiplication of **matrix q_grid** x **indexed_k_grid**

here is the sizes of such matrixes: 

the size of matrix q_grid is torch.Size([32, 128, **49**])
the size of indexed_k_grid is torch.Size([32, 128, **3136**])

and those are the numbers mentioned in the error : 
`
The size of tensor a (49) must match the size of tensor b (3136) at non-singleton dimension 2`

taking into considration that this error occures when i remove the GlobalAveragePooling. 

now i don't know how can i change the dimensions of such matrix ,so that the functionality of densecl will not be changed as well as the error will disappear. 


here is the inner code of  [densecl](https://github.com/open-mmlab/mmpretrain/blob/main/mmpretrain/models/selfsup/densecl.py)
any suggestions please?
