### ISSUE TITLE
[Bug]     raise ValueError( ValueError: Input dimension should be at least 3

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmpretrain#1558]
### Branch

main branch (mmpretrain version)

### Describe the bug

I try to train a model of simclr with a new bacbone of HRnet-w32 

 This is the error that i got after training the model:
  ```
 raise ValueError(
ValueError: Input dimension should be at least 3
```
my configuration is as bellow: 

`
dataset_type = 'CustomDataset'
data_root = '/work/shubbak/datasets/ACID/'
data_preprocessor = dict(
    type='SelfSupDataPreprocessor',
    mean=[123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375],
    to_rgb=True)
view_pipeline = [
    dict(
        type='RandomResizedCrop',
        scale=224,
        crop_ratio_range=(0.2, 1.0),
        backend='pillow'),
    dict(
        type='RandomApply',
        transforms=[
            dict(
                type='ColorJitter',
                brightness=0.4,
                contrast=0.4,
                saturation=0.4,
                hue=0.1)
        ],
        prob=0.8),
    dict(
        type='RandomGrayscale',
        prob=0.2,
        keep_channels=True,
        channel_weights=(0.114, 0.587, 0.2989)),
    dict(
        type='GaussianBlur',
        magnitude_range=(0.1, 2.0),
        magnitude_std='inf',
        prob=0.5),
    dict(type='RandomFlip', prob=0.5)
]
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiView',
        num_views=2,
        transforms=[[{
            'type': 'RandomResizedCrop',
            'scale': 224,
            'crop_ratio_range': (0.2, 1.0),
            'backend': 'pillow'
        }, {
            'type':
            'RandomApply',
            'transforms': [{
                'type': 'ColorJitter',
                'brightness': 0.4,
                'contrast': 0.4,
                'saturation': 0.4,
                'hue': 0.1
            }],
            'prob':
            0.8
        }, {
            'type': 'RandomGrayscale',
            'prob': 0.2,
            'keep_channels': True,
            'channel_weights': (0.114, 0.587, 0.2989)
        }, {
            'type': 'GaussianBlur',
            'magnitude_range': (0.1, 2.0),
            'magnitude_std': 'inf',
            'prob': 0.5
        }, {
            'type': 'RandomFlip',
            'prob': 0.5
        }]]),
    dict(type='PackInputs')
]
train_dataloader = dict(
    pin_memory=True,
    persistent_workers=True,
    collate_fn=dict(type='default_collate'),
    batch_size=32,
    num_workers=5,
    dataset=dict(
        type='CustomDataset',
        data_root='/work/shubbak/datasets/ACID/',
        data_prefix='ACID_Images',
        with_label=False,
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiView',
                num_views=2,
                transforms=[[{
                    'type': 'RandomResizedCrop',
                    'scale': 224,
                    'crop_ratio_range': (0.2, 1.0),
                    'backend': 'pillow'
                }, {
                    'type':
                    'RandomApply',
                    'transforms': [{
                        'type': 'ColorJitter',
                        'brightness': 0.4,
                        'contrast': 0.4,
                        'saturation': 0.4,
                        'hue': 0.1
                    }],
                    'prob':
                    0.8
                }, {
                    'type': 'RandomGrayscale',
                    'prob': 0.2,
                    'keep_channels': True,
                    'channel_weights': (0.114, 0.587, 0.2989)
                }, {
                    'type': 'GaussianBlur',
                    'magnitude_range': (0.1, 2.0),
                    'magnitude_std': 'inf',
                    'prob': 0.5
                }, {
                    'type': 'RandomFlip',
                    'prob': 0.5
                }]]),
            dict(type='PackInputs')
        ]),
    sampler=dict(type='DefaultSampler', shuffle=True))
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='LARS', lr=0.3, weight_decay=1e-06, momentum=0.9),
    paramwise_cfg=dict(
        custom_keys=dict({
            'bn': dict(decay_mult=0, lars_exclude=True),
            'bias': dict(decay_mult=0, lars_exclude=True),
            'downsample.1': dict(decay_mult=0, lars_exclude=True)
        })))
param_scheduler = [
    dict(
        type='LinearLR',
        start_factor=0.0001,
        by_epoch=True,
        begin=0,
        end=10,
        convert_to_iter_based=True),
    dict(
        type='CosineAnnealingLR', T_max=190, by_epoch=True, begin=10, end=200)
]
train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=400, val_interval=10)
default_scope = 'mmpretrain'
default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=10),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(type='CheckpointHook', interval=10),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='VisualizationHook', enable=False))
env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    type='UniversalVisualizer', vis_backends=[dict(type='LocalVisBackend')])
log_level = 'INFO'
load_from = None
resume = False
randomness = dict(seed=None, deterministic=False)
model = dict(
    type='SimCLR',
    backbone=dict(type='HRNet', arch='w32'),
    neck=[
        dict(type='HRFuseScales', in_channels=(32, 64, 128, 256)),
        dict(type='GlobalAveragePooling'),
        dict(
            type='NonLinearNeck',
            in_channels=2048,
            hid_channels=2048,
            out_channels=128,
            num_layers=2,
            with_avg_pool=True)
    ],
    head=dict(
        type='ContrastiveHead',
        loss=dict(type='CrossEntropyLoss'),
        temperature=0.1))
auto_scale_lr = dict(base_batch_size=128)
launcher = 'none'
work_dir = 'train_dir/ACID_all/simclr_HRnet-w32/'

`

### Environment

```
{'sys.platform': 'linux',
 'Python': '3.8.11 (default, Jul 13 2021, 14:00:03) [GCC 4.8.5 20150623 (Red '
           'Hat 4.8.5-44)]',
 'CUDA available': True,
 'numpy_random_seed': 2147483648,
 'GPU 0': 'Tesla V100-SXM2-32GB',
 'CUDA_HOME': '/usr/local/cuda',
 'NVCC': 'Cuda compilation tools, release 12.1, V12.1.105',
 'GCC': 'gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)',
 'PyTorch': '2.0.0+cu117',
 'TorchVision': '0.15.1+cu117',
 'OpenCV': '4.7.0',
 'MMEngine': '0.7.3',
 'MMCV': '2.0.0',
 'MMPreTrain': '1.0.0rc7+e80418a'}

```

### Other information

I did some modification on the backbone ,and neck of normal HRnet to be compatable with the simclr model. 
as simclr model (in this repository )are based on ResNet 50 

my new model become as bellow : 
`

```
model = dict(
    type='SimCLR',
    backbone=dict(type='HRNet', arch='w32'),  
    neck=[
        dict(type='HRFuseScales', in_channels=(32, 64, 128, 256)),
        dict(type='GlobalAveragePooling'),
        dict(type='NonLinearNeck',  # SimCLR non-linear neck
        in_channels=2048,
        hid_channels=2048,
        out_channels=128,
        num_layers=2,
        with_avg_pool=True),
        ],
    head=dict(
        type='ContrastiveHead',
        loss=dict(type='CrossEntropyLoss'),
        temperature=0.1),     
      )

```

`

i am not sure what will be exactly the issue , can you help me please?

**Comment by fangyixiao18** [comment]
could provide your full error log？

**Comment by alaa-shubbak** [comment]
Thanks for response . here the full error log : 

```
File "tools/train.py", line 160, in <module>
    main()
  File "tools/train.py", line 156, in main
    runner.train()
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1721, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/shubbak/mmpretrain/mmpretrain/models/selfsup/base.py", line 127, in forward
    return self.loss(inputs, data_samples)
  File "/scratch/shubbak/mmpretrain/mmpretrain/models/selfsup/simclr.py", line 80, in loss
    z = self.neck(x)[0]  # (2n)xd
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/shubbak/mmpretrain/mmpretrain/models/necks/nonlinear_neck.py", line 104, in forward
    x = self.avgpool(x)
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/torch/nn/modules/pooling.py", line 1196, in forward
    return F.adaptive_avg_pool2d(input, self.output_size)
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/torch/nn/functional.py", line 1213, in adaptive_avg_pool2d
    _output_size = _list_with_default(output_size, input.size())
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/torch/nn/modules/utils.py", line 37, in _list_with_default
    raise ValueError(
ValueError: Input dimension should be at least 3
```

**Comment by bryanbocao** [comment]
Could you print the shape of ```data_batch```?

**Comment by alaa-shubbak** [comment]
> Could you print the shape of `data_batch`?

i have batch_size=32

**Comment by bryanbocao** [comment]
I meant the specific shape of ```data_batch``` like ```(32, 3, 224, 224)```, not just the batch_size. The error message indicates that something might be wrong with the input.

**Comment by bryanbocao** [comment]
I meant the specific **shape** of ```data_batch``` like ```(32, 3, 224, 224)```, not just the batch_size (they are different things). The error message 
```
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
```
indicates that the input's shape migth not be matched with the expected shape.

Probably also print out ```data_batch``` to debug.

**Comment by alaa-shubbak** [comment]
i try to print it . 
i modify the loop.py as bellow:
<img width="312" alt="image" src="https://github.com/open-mmlab/mmpretrain/assets/10245810/85af1c01-bd3c-422e-8e8d-a276242c5035">

but i could not print the value .
how can i do so.

**Comment by bryanbocao** [comment]
Could you print it before this line ```self.run_iter(idx, data_batch)``` that causes the error?

For shape try
```
print(data_batch.size())
```
or
```
print(np.shape(data_batch))
```

**Comment by alaa-shubbak** [comment]
the first command gives me this 

```
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/runner/loops.py", line 113, in run_epoch
    print(data_batch.size())
AttributeError: 'dict' object has no attribute 'size'
```


while the second command gives me 
```
File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/runner/loops.py", line 114, in run_epoch
    print(np.shape(data_batch))
NameError: name 'np' is not defined
```

**Comment by alaa-shubbak** [comment]
i import numpy library . 
and run it but it did not gives me any info 
<img width="530" alt="image" src="https://github.com/open-mmlab/mmpretrain/assets/10245810/5c6e9b4c-009d-4ba0-b8a2-92f6f57645f4">

**Comment by bryanbocao** [comment]
It shows that ```data_batch``` is a dictionary, which is not what it expects.

You may trace back to the previous data flow how ```data_batch``` is defined.

**Comment by alaa-shubbak** [comment]
- for my dataset under folder ACID , it is only images a I trained the model with self-supervised appraoch. so i do not have any annotation files. 
- my modification was only within the config files in the model folder , i did not modify any thing outside [this](https://github.com/open-mmlab/mmpretrain/tree/main/configs/simclr)

- here is my config : 
_base_ = [
    #'../_base_/models/hrnet/hrnet-w32.py',
    '../_base_/datasets/ACID_bs32_pil_resize.py',
    '../_base_/schedules/imagenet_lars_coslr_200e.py',
    '../_base_/default_runtime.py'
]

# new model settings for HRnet
model = dict(
    type='SimCLR',
    backbone=dict(type='HRNet', arch='w32'), 
      #combine simclr and HRnet neck together
      neck=[
    #modify here according to HRnet
        dict(type='HRFuseScales', in_channels=(32, 64, 128, 256)),
        dict(type='GlobalAveragePooling'),
        dict(type='NonLinearNeck',  # SimCLR non-linear neck
        in_channels=2048,
        hid_channels=2048,
        out_channels=128,
        num_layers=2,
        with_avg_pool=True)
        ],
    head=dict(
        type='ContrastiveHead',
        loss=dict(type='CrossEntropyLoss'),
        temperature=0.1)
        )


train_cfg = dict(max_epochs=400, val_interval=10)  # Train for 300 epochs, evaluate every 10 epochs

# optimizer
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='LARS', lr=0.3, momentum=0.9, weight_decay=1e-6),
    paramwise_cfg=dict(
        custom_keys={
            'bn': dict(decay_mult=0, lars_exclude=True),
            'bias': dict(decay_mult=0, lars_exclude=True),
            # bn layer in ResNet block downsample module
            'downsample.1': dict(decay_mult=0, lars_exclude=True),
        }))

# runtime settings
default_hooks = dict(
    # only keeps the latest 3 checkpoints
    #checkpoint=dict(type='CheckpointHook', interval=10, max_keep_ckpts=3))
    checkpoint=dict(type='CheckpointHook', interval=10),
     logger=dict(type='LoggerHook', interval=10)
    )


# NOTE: `auto_scale_lr` is for automatically scaling LR
# based on the actual training batch size.
# base_batch_size = (4 GPUs) x (32 samples per GPU)
auto_scale_lr = dict(base_batch_size=256)

**Comment by alaa-shubbak** [comment]
sorry i did modification on the creation of dataset in _base_ folder as bellow 

# dataset settings
dataset_type = 'CustomDataset'
data_root = '/work/shubbak/datasets/ACID/'
data_preprocessor = dict(
    type='SelfSupDataPreprocessor',
    #update numebr of classes
    #num_classes=1,
    # RGB format normalization parameters
    mean=[123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375],
    # convert image from BGR to RGB
    to_rgb=True)

#add view_pipeline line here
view_pipeline = [
   dict(
        type='RandomResizedCrop',
        scale=224,
        crop_ratio_range=(0.2, 1.),
        backend='pillow'),
    dict(
        type='RandomApply',
        transforms=[
            dict(
               type='ColorJitter',
                brightness=0.4,
                contrast=0.4,
                saturation=0.4,
                hue=0.1)
        ],
        prob=0.8),
   dict(
       type='RandomGrayscale',
        prob=0.2,
        keep_channels=True,
        channel_weights=(0.114, 0.587, 0.2989)),
    dict(
        type='GaussianBlur',
        magnitude_range=(0.1, 2.0),
        magnitude_std='inf',
        prob=0.5),
    dict(type='RandomFlip', prob=0.5),
 ]
train_pipeline = [
    dict(type='LoadImageFromFile'),
    #dict(type='RandomResizedCrop', scale=224, backend='pillow'),
    #dict(type='RandomFlip', prob=0.5, direction='horizontal'),
    dict(type='MultiView', num_views=2, transforms=[view_pipeline]),
    dict(type='PackInputs')
]

train_dataloader = dict(
    batch_size=32,
    num_workers=5,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    collate_fn=dict(type='default_collate'),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        #ann_file='meta/train.txt',
        data_prefix=dict(img_path='ACID_Images/'),
        with_label=False,
        #classes=['excavator',],
        pipeline=train_pipeline)
        )

**Comment by bryanbocao** [comment]
Can you show the structure of ```/work/shubbak/datasets/ACID/``` in your file system?

**Comment by alaa-shubbak** [comment]
thanks for reply . I already use the same data in ACID folder for training the normal Simclr model . 
it works fine with them. and no error appeared as i have no annotation info and no test and val pipeline and dataloader. 

ACID folder has the following files : 

<img width="491" alt="image" src="https://github.com/open-mmlab/mmpretrain/assets/10245810/926efa26-a2e5-4c9b-8275-10a81f2640d5">

i only took the first folder ,which has all the images and i ignore any annotation files. 
also i did not mention the classes within my dataset. as bellow : 
<img width="245" alt="image" src="https://github.com/open-mmlab/mmpretrain/assets/10245810/403a771a-fdd8-4d62-9684-c6fab53a46e3">
 is that true ? it is not fit directly with mmclassification, but as i understood it fit with the self-supervised approach and the simclr method. 
it is typically with the one in this [doc.](https://mmpretrain.readthedocs.io/en/latest/user_guides/dataset_prepare.html)

**Comment by bryanbocao** [comment]
> i import numpy library . and run it but it did not gives me any info <img alt="image" width="530" src="https://user-images.githubusercontent.com/10245810/238035238-5c6e9b4c-009d-4ba0-b8a2-92f6f57645f4.png">

The ```()``` probably means that it does not load any images.


What's the structure inside ```ACID_Imaeges```? I assume it is in the similar format of
```
ACID_Imaeges/
├── class_x
│   ├── xxx.png
│   ├── xxy.png
│   └── ...
│       └── xxz.png
└── class_y
    ├── 123.png
    ├── nsdf3.png
    ├── ...
    └── asd932_.png
```
?

**Comment by bryanbocao** [comment]
I guess it's the '/' in the first character in ```data_root = '/work/shubbak/datasets/ACID/'``` that causes the problem

How about
```
data_root = 'work/shubbak/datasets/ACID/'
```

**Comment by alaa-shubbak** [comment]
here is the  full directory psth of my dataset (after print pwd)

<img width="166" alt="image" src="https://github.com/open-mmlab/mmpretrain/assets/10245810/5f51aa0e-2030-40fa-ae8a-4a8a8a55214f">

I try also this 
> data_root = 'work/shubbak/datasets/ACID/'

but it gives me this error 
<img width="855" alt="image" src="https://github.com/open-mmlab/mmpretrain/assets/10245810/eaca83b2-c078-4e7f-9b73-2c50f74cb3cc">

here it is 

```
Traceback (most recent call last):
  File "tools/train.py", line 160, in <module>
    main()
  File "tools/train.py", line 156, in main
    runner.train()
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1687, in train
    self._train_loop = self.build_train_loop(
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1479, in build_train_loop
    loop = LOOPS.build(
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/shubbak/pose_env2/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
FileNotFoundError: class `EpochBasedTrainLoop` in mmengine/runner/loops.py: class `CustomDataset` in mmpretrain/datasets/custom.py: [Errno 2] No such file or directory: 'work/shubbak/datasets/ACID/ACID_Images/'

```

**Comment by alaa-shubbak** [comment]
to explain my target : i want to pretrain a model of simclr on new backbone of HRnet instead of ResNet-50 
so i follow this document for create my custom dataset:
https://mmpretrain.readthedocs.io/en/latest/notes/pretrain_custom_dataset.html

as the model is simclr (self-supervised approach) , i decide to but all images in one folder called ACID/ACID_Images 

actually , i don't want to use this pretrained model for classification neither for object detection . i want to use it for another vision downstream task. 

later on , i will use the model for fine-tuning on  a dataset has a keypoint and pose estimation annotation format. 

but untill now the model was unable to pretrained , as the backbone is changed .

**Comment by alaa-shubbak** [comment]
I test those command for loading and visualization of  the images : 
`python ./tools/visualization/browse_dataset.py ./configs/simclr/hrnet-w32_4xb32_simclr_ACID_All.py --phase train --output-dir tmp --mode original --show-number 100 --rescale-factor 10 --channel-order RGB`

and 
`python ./tools/visualization/browse_dataset.py configs/simclr/hrnet-w32_4xb32_simclr_ACID_All.py -n 10 -m concat`

both of them work correctly and produce image and transformed images . 
I think this means that my model is loading the dataset correctly . so i think the issue is within the config that i produced. 

I mentioned before , i try to develop it so i am not sure if my idea and the way of combining  the hrnet backbone with the body of simclr approach was correct.
