### ISSUE TITLE
[Bug] Run demo error

### ISSUE THREAD

**Issue by Fau818** [open-mmlab/mmpretrain#1560]
### Branch

main branch (mmpretrain version)

### Describe the bug

I installed the mmpretrain according to the [documentation](https://mmdetection.readthedocs.io/en/latest/get_started.html), but failed in `Verify the installation` section.

The following is the error message (copied from terminal).

```
~/Documents/Fau/Projects.nosync/Python_Projects/mmpretrain (main) » python demo/image_demo.py demo/demo.JPEG resnet18_8xb32_in1k --device cpu
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmclassification/v0/resnet/resnet18_8xb32_in1k_20210831-fbbb1da6.pth
Inference ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Traceback (most recent call last):
  File "/Users/Fau/Documents/Fau/Projects.nosync/Python_Projects/mmpretrain/demo/image_demo.py", line 44, in <module>
    main()
  File "/Users/Fau/Documents/Fau/Projects.nosync/Python_Projects/mmpretrain/demo/image_demo.py", line 37, in main
    result = inferencer(args.img, show=args.show, show_dir=args.show_dir)[0]
  File "/Users/Fau/Documents/Fau/Projects.nosync/Python_Projects/mmpretrain/mmpretrain/apis/image_classification.py", line 123, in __call__
    return super().__call__(inputs, return_datasamples, batch_size,
  File "/usr/local/Caskroom/miniconda/base/envs/dl/lib/python3.10/site-packages/mmengine/infer/infer.py", line 221, in __call__
    results = self.postprocess(preds, visualization, return_datasamples,
  File "/Users/Fau/Documents/Fau/Projects.nosync/Python_Projects/mmpretrain/mmpretrain/apis/image_classification.py", line 221, in postprocess
    result['pred_class'] = self.classes[pred_label]
IndexError: list index out of range
```

### Environment

```python
{'sys.platform': 'darwin',
 'Python': '3.10.10 (main, Mar 21 2023, 13:41:39) [Clang 14.0.6 ]',
 'CUDA available': False,
 'numpy_random_seed': 2147483648,
 'GCC': 'Homebrew clang version 16.0.2',
 'PyTorch': '2.0.0',
 'TorchVision': '0.15.1',
 'OpenCV': '4.7.0',
 'MMEngine': '0.7.3',
 'MMCV': '2.0.0',
 'MMPreTrain': '1.0.0rc7+e80418a'}
```

### Other information

MacBook Pro 16-inch (Inter) MacOS 13.3.1a

**Comment by Ezra-Yu** [comment]
Sorry that I can not reproduce your error.

Can you run the following command in ipython?

![image](https://github.com/open-mmlab/mmpretrain/assets/18586273/f048e2f1-f527-4d57-b26b-196e50d10a8a)

**Comment by Fau818** [comment]
> Sorry that I can not reproduce your error.
> 
> Can you run the following command in ipython?
> 
> ![image](https://user-images.githubusercontent.com/18586273/237868982-f048e2f1-f527-4d57-b26b-196e50d10a8a.png)

I tried and got an error.

```python

In [1]: from mmpretrain import list_models, get_model
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 from mmpretrain import list_models, get_model

File ~/Documents/Fau/Projects.nosync/Python_Projects/mmpretrain/mmpretrain/__init__.py:2
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 import mmcv
      3 import mmengine
      4 from mmengine.utils import digit_version

ModuleNotFoundError: No module named 'mmcv'

In [2]: !python3 -m pip list | grep mmcv
mmcv                    2.0.0

```

**Comment by Ezra-Yu** [comment]
try to uninstall and install mmcv:

```
mim uninstall mmcv
mim install mmcv
```

**Comment by Fau818** [comment]
> try to uninstall and install mmcv:
> 
> ```
> mim uninstall mmcv
> mim install mmcv
> ```

It doesn't work for me, and the same error come again.

**Comment by Ezra-Yu** [comment]
So in your Python console, can you run ```import mmcv``` successfully?

there may be something wrong with the installation of mmcv,

**Comment by Fau818** [comment]
I tried several times to reinstall mmpretrain in different environments, but all failed.

In current envirment, mmdet could work as expect.

**Comment by Ezra-Yu** [comment]
which is your version of mmdet?

**Comment by Fau818** [comment]
> So in your Python console, can you run `import mmcv` successfully?
> 
> there may be something wrong with the installation of mmcv,

Sorry! I made an mistake, my ipython doesn't use my current python environment. I tried to import `mmcv` in a python file, the error doesn't occur.

---

I can run the following code in python file without any error.

```python
from mmpretrain import list_models, get_model
import torch

list_models("*resnet50*rsb*")

model = get_model('resnet50_8xb256-rsb-a1-600e_in1k', device='cpu')

x = torch.rand((1, 3, 224, 224))

model(x)[0].shape
```

**Comment by Ezra-Yu** [comment]
ok. This indicates that you have successfully installed mmpretrain.

**Comment by Fau818** [comment]
Now, I've checked my python, ipython, and pip command, and I can guarantee they are in a same expected environment.

I tried both two ways in `Verify the installation` section, the same error was gotten.

shell command:

```zsh
python demo/image_demo.py demo/demo.JPEG resnet18_8xb32_in1k --device cpu
```

python script:

```python
from mmpretrain import get_model, inference_model

model = get_model('resnet18_8xb32_in1k', device='cpu')  # 或者 device='cuda:0'
inference_model(model, 'demo/demo.JPEG')
```

the same error:
<img width="1426" alt="image" src="https://github.com/open-mmlab/mmpretrain/assets/75115028/86d6fd88-a9a7-4c75-9799-1fda69883093">

**Comment by Ezra-Yu** [comment]
Can you run this? check the classes number, should be 1000.
![image](https://github.com/open-mmlab/mmpretrain/assets/18586273/cd5d3f3b-7502-4711-8345-da82bf91bf2f)

**Comment by Fau818** [comment]
> Can you run this? check the classes number, should be 1000.
> ![image](https://user-images.githubusercontent.com/18586273/237881548-cd5d3f3b-7502-4711-8345-da82bf91bf2f.png)

Sure!

<img width="1048" alt="image" src="https://github.com/open-mmlab/mmpretrain/assets/75115028/2b42790c-b6ee-4cd8-b733-f13a9fdf1e5a">

**Comment by Ezra-Yu** [comment]
? then `python demo/image_demo.py demo/demo.JPEG resnet50_8xb32_in1k` still has the above error? I am confused.

**Comment by Fau818** [comment]
Yes, the same mistakes always surround me.

I record a video to show this.

https://github.com/open-mmlab/mmpretrain/assets/75115028/43266a74-caa3-4c8b-ad1b-c381517576fb

---

Sorry for the late reply, the video just could not be uploaded.

**Comment by Ezra-Yu** [comment]
If you can run the following commands, I think your installation is successful, you can use the mmpretrain regardless of this error. I will locate the error later.
```
In [1]: from mmpretrain import get_model, list_models

In [2]: list_models("*resnet50*rsb*")
Out[2]: 
['resnet50_8xb256-rsb-a1-600e_in1k',
 'resnet50_8xb256-rsb-a2-300e_in1k',
 'resnet50_8xb256-rsb-a3-100e_in1k']

In [3]: model = get_model('resnet50_8xb256-rsb-a1-600e_in1k', pretrained=True).cuda()
05/12 14:26:25 - mmengine - INFO - Because batch augmentations are enabled, the data preprocessor automatically enables the `to_onehot` option to generate one-hot format labels.
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_8xb256-rsb-a1-600e_in1k_20211228-20e21305.pth

In [4]: import torch

In [5]: x = torch.rand((1, 3, 224, 224)).cuda()

In [6]: model(x)[0].shape
/home/PJLAB/yuzhaohui/softwares/miniconda3/envs/pretrain/lib/python3.9/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448255797/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Out[6]: torch.Size([1000])
```

**Comment by Fau818** [comment]
> If you can run the following commands, I think your installation is successful, you can use the mmpretrain regardless of this error. I will locate the error later.
> 
> ```
> In [1]: from mmpretrain import get_model, list_models
> 
> In [2]: list_models("*resnet50*rsb*")
> Out[2]: 
> ['resnet50_8xb256-rsb-a1-600e_in1k',
>  'resnet50_8xb256-rsb-a2-300e_in1k',
>  'resnet50_8xb256-rsb-a3-100e_in1k']
> 
> In [3]: model = get_model('resnet50_8xb256-rsb-a1-600e_in1k', pretrained=True).cuda()
> 05/12 14:26:25 - mmengine - INFO - Because batch augmentations are enabled, the data preprocessor automatically enables the `to_onehot` option to generate one-hot format labels.
> Loads checkpoint by http backend from path: https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_8xb256-rsb-a1-600e_in1k_20211228-20e21305.pth
> 
> In [4]: import torch
> 
> In [5]: x = torch.rand((1, 3, 224, 224)).cuda()
> 
> In [6]: model(x)[0].shape
> /home/PJLAB/yuzhaohui/softwares/miniconda3/envs/pretrain/lib/python3.9/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448255797/work/c10/core/TensorImpl.h:1156.)
>   return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
> Out[6]: torch.Size([1000])
> ```

Yes, I could correctly run the code with cpu version (shown in the following).

```python
from mmpretrain import get_model, list_models
import torch

print(list_models("*resnet50*rsb*"))
model = get_model('resnet50_8xb256-rsb-a1-600e_in1k', pretrained=True)


x = torch.rand((1, 3, 224, 224))

print(model(x)[0].shape)
```

And if there is anything I can do to help you, I will be very glad to help!

**Comment by Ezra-Yu** [comment]
Yes, Just debug the demo, 
```
~/Documents/Fau/Projects.nosync/Python_Projects/mmpretrain (main) » python demo/image_demo.py demo/demo.JPEG resnet18_8xb32_in1k --device cpu
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmclassification/v0/resnet/resnet18_8xb32_in1k_20210831-fbbb1da6.pth
Inference ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Traceback (most recent call last):
  File "/Users/Fau/Documents/Fau/Projects.nosync/Python_Projects/mmpretrain/demo/image_demo.py", line 44, in <module>
    main()
  File "/Users/Fau/Documents/Fau/Projects.nosync/Python_Projects/mmpretrain/demo/image_demo.py", line 37, in main
    result = inferencer(args.img, show=args.show, show_dir=args.show_dir)[0]
  File "/Users/Fau/Documents/Fau/Projects.nosync/Python_Projects/mmpretrain/mmpretrain/apis/image_classification.py", line 123, in __call__
    return super().__call__(inputs, return_datasamples, batch_size,
  File "/usr/local/Caskroom/miniconda/base/envs/dl/lib/python3.10/site-packages/mmengine/infer/infer.py", line 221, in __call__
    results = self.postprocess(preds, visualization, return_datasamples,
  File "/Users/Fau/Documents/Fau/Projects.nosync/Python_Projects/mmpretrain/mmpretrain/apis/image_classification.py", line 221, in postprocess
    result['pred_class'] = self.classes[pred_label]
IndexError: list index out of range
```

Find what actually `pred_label` and `inferencer.classes` are. here is the [code1](https://github.com/open-mmlab/mmpretrain/blob/e80418a424aaefb81c95df458216bb3e9af246c4/demo/image_demo.py#LL29C8-L29C8),  [code2](https://github.com/open-mmlab/mmpretrain/blob/e80418a424aaefb81c95df458216bb3e9af246c4/mmpretrain/apis/image_classification.py#L203).

**Comment by Fau818** [comment]
It seems the problem in `pred_label`.

I add a `print()` function to show `data_sample`.

code2 modified:

<img width="864" alt="image" src="https://github.com/open-mmlab/mmpretrain/assets/75115028/34a1cf49-b057-477c-b8eb-8917b57f5be7">

And I got this.

![3929c084443e2938712e923b1fbe1348](https://github.com/open-mmlab/mmpretrain/assets/75115028/fe7f5b6f-b85a-4e8e-bb13-78754d19beb6)

**Comment by Ezra-Yu** [comment]
> 'PyTorch': '2.0.0',

Maybe is cause by the version of `torch.argmax()` should return a max index in torch1.11

![image](https://github.com/open-mmlab/mmpretrain/assets/18586273/9e6b84ba-0db7-45b4-9134-d424bb4d7a4d)

**Comment by Ezra-Yu** [comment]
but in the doc of torch 2.0. the `torch. argmax` still returns the torch.Long. refer to https://pytorch.org/docs/stable/generated/torch.argmax.html

**Comment by Ezra-Yu** [comment]
Sorry, I see `pred_label` as a floating point number.

 It looks like that it is a bug of torch2.0 on 'mps' devices.

**Comment by Ezra-Yu** [comment]
There has been the same issue in PyTorch refer to https://github.com/pytorch/pytorch/issues/92311.
