### ISSUE TITLE
'UniversalVisualizer is not in the visualizer registry. Please check whether the value of `UniversalVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

### ISSUE THREAD

**Issue by Xuchangsheng1** [open-mmlab/mmpretrain#1566]
### 分支

main 分支 (mmpretrain 版本)

### 描述该错误

mmengine - WARNING - Failed to import `None.registry` make sure the registry.py exists in `None` package.
05/16 17:24:55 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "visualizer" registry tree. As a workaround, the current "visualizer" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "tools/train.py", line 159, in <module>
    main()
  File "tools/train.py", line 152, in main
    runner = Runner.from_cfg(cfg)
  File "/home/xcs/anaconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 439, in from_cfg
    runner = cls(
  File "/home/xcs/anaconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 393, in __init__
    self.visualizer = self.build_visualizer(visualizer)
  File "/home/xcs/anaconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 780, in build_visualizer
    return VISUALIZERS.build(visualizer)
  File "/home/xcs/anaconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/xcs/anaconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'UniversalVisualizer is not in the visualizer registry. Please check whether the value of `UniversalVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

### 环境信息

05/16 17:30:13 - mmengine - WARNING - Failed to import `None.registry` make sure the registry.py exists in `None` package.
05/16 17:30:13 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "visualizer" registry tree. As a workaround, the current "visualizer" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "tools/train.py", line 159, in <module>
    main()
  File "tools/train.py", line 152, in main
    runner = Runner.from_cfg(cfg)
  File "/home/xcs/anaconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 439, in from_cfg
    runner = cls(
  File "/home/xcs/anaconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 393, in __init__
    self.visualizer = self.build_visualizer(visualizer)
  File "/home/xcs/anaconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 780, in build_visualizer
    return VISUALIZERS.build(visualizer)
  File "/home/xcs/anaconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/xcs/anaconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'UniversalVisualizer is not in the visualizer registry. Please check whether the value of `UniversalVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by Xuchangsheng1** [comment]
mmcv                               2.0.0rc4
mmengine                           0.7.3
mmpretrain                         1.0.0rc7

**Comment by Xuchangsheng1** [comment]
_base_ = [
    '../_base_/models/resnest50.py',
    '../_base_/datasets/imagenet_bs64.py',
    '../_base_/default_runtime.py',
    './_randaug_policies.py',
]
# model settings
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='ResNeSt',
        depth=50,
        num_stages=4,
        out_indices=(3,),
        style='pytorch'),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=7,
        in_channels=2048,
        loss=dict(
            type='LabelSmoothLoss',
            label_smooth_val=0.1,
            num_classes=7,
            reduction='mean',
            loss_weight=1.0),
        topk=(1, 5),
        cal_acc=False),
    train_cfg=dict(augments=dict(type='Mixup', alpha=0.2)),
)

# dataset settings
dataset_type = 'ImageNet'


data_root = '/media/disk/xcs/data/QCS/SPBTest_split/'
data_preprocessor = dict(
    num_classes=7,
    # RGB format normalization parameters
    mean=[123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375],
    # convert image from BGR to RGB
    to_rgb=True,
)

# lighting params, in order of BGR
EIGVAL = [55.4625, 4.7940, 1.1475]
EIGVEC = [
    [-0.5836, -0.6948, 0.4203],
    [-0.5808, -0.0045, -0.8140],
    [-0.5675, 0.7192, 0.4009],
]

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='RandAugment',
        policies={{_base_.policies}},
        num_policies=2,
        magnitude_level=12),
    dict(type='EfficientNetRandomCrop', scale=224, backend='pillow'),
    dict(type='RandomFlip', prob=0.5, direction='horizontal'),
    dict(type='ColorJitter', brightness=0.4, contrast=0.4, saturation=0.4),
    dict(
        type='Lighting',
        eigval=EIGVAL,
        eigvec=EIGVEC,
        alphastd=0.1,
        to_rgb=False),
    dict(type='PackInputs'),
]

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='EfficientNetCenterCrop', crop_size=256, backend='pillow'),
    dict(type='PackInputs'),
]

train_dataloader = dict(
    batch_size=64,
    num_workers=5,
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix='train',
        ann_file=data_root + 'meta/train.txt',
        classes=classes,
        pipeline=train_pipeline),
    sampler=dict(type='DefaultSampler', shuffle=True),
)

val_dataloader = dict(
    batch_size=64,
    num_workers=5,
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix='val',
        ann_file=data_root + 'meta/val.txt',
        classes=classes,
        pipeline=test_pipeline),
    sampler=dict(type='DefaultSampler', shuffle=False),
)
# val_evaluator = dict(type='Accuracy', topk=(1, 5))
val_evaluator = [
    dict(type='Accuracy', topk=(1, 5)),
    dict(type='SingleLabelMetric', items=['precision', 'recall']),
]

# If you want standard test, please manually configure the test dataset
test_dataloader = val_dataloader
test_evaluator = val_evaluator



# train_dataloader = dict(dataset=dict(pipeline=train_pipeline))
# val_dataloader = dict(dataset=dict(pipeline=test_pipeline))
# test_dataloader = dict(dataset=dict(pipeline=test_pipeline))

# schedule settings
optim_wrapper = dict(
    optimizer=dict(type='SGD', lr=0.8, momentum=0.9, weight_decay=1e-4),
    paramwise_cfg=dict(bias_decay_mult=0., norm_decay_mult=0.),
)

param_scheduler = [
    # warm up learning rate scheduler
    dict(
        type='LinearLR',
        start_factor=1e-6,
        by_epoch=True,
        begin=0,
        end=5,
        # update by iter
        convert_to_iter_based=True),
    # main learning rate scheduler
    dict(
        type='CosineAnnealingLR',
        T_max=265,
        by_epoch=True,
        begin=5,
        end=270,
    )
]

train_cfg = dict(by_epoch=True, max_epochs=270)
# 使用默认的验证循环控制器
val_cfg = dict()
# 使用默认的测试循环控制器
test_cfg = dict()
# NOTE: `auto_scale_lr` is for automatically scaling LR
# based on the actual training batch size.
# base_batch_size = (32 GPUs) x (64 samples per GPU)
auto_scale_lr = dict(base_batch_size=2048)

# defaults to use registries in mmpretrain
default_scope = 'mmpretrain'

# configure default hooks
default_hooks = dict(
    # record the time of every iteration.
    timer=dict(type='IterTimerHook'),

    # print log every 100 iterations.
    logger=dict(type='LoggerHook', interval=100),

    # enable the parameter scheduler.
    param_scheduler=dict(type='ParamSchedulerHook'),

    # save checkpoint per epoch.
    checkpoint=dict(type='CheckpointHook', interval=1, save_best="auto", max_keep_ckpts=50),

    # set sampler seed in distributed evrionment.
    sampler_seed=dict(type='DistSamplerSeedHook'),

    # validation results visualization, set True to enable it.
    visualization=dict(type='VisualizationHook', enable=False),
)

# configure environment
env_cfg = dict(
    # whether to enable cudnn benchmark
    cudnn_benchmark=False,

    # set multi process parameters
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),

    # set distributed parameters
    dist_cfg=dict(backend='nccl'),
)

# set visualizer
# vis_backends = [dict(type='LocalVisBackend')]
vis_backends = [
    dict(type='LocalVisBackend'),
    dict(type='TensorboardVisBackend'),
]

visualizer = dict(type='UniversalVisualizer', vis_backends=vis_backends)

# set log level
log_level = 'INFO'

# load from which checkpoint
load_from = None

# whether to resume training from the loaded checkpoint
resume = False

# Defaults to use random seed and disable `deterministic`
randomness = dict(seed=None, deterministic=False)
work_dir = '/media/disk/xcs/mmcls/resnest50_spb/work_dirs'

**Comment by FlyingRocCui** [comment]
The branch v1.0.0rc6 is ok！

**Comment by alaa-shubbak** [comment]
i got same error , and i try to install mmcv==2.0.0rc4 
I run this command 

`pip install mmcv==2.0.0rc4`

as well as this 

`mim install mmcv==2.0.0rc4`

and i get this error for both trying ,
```

     RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv
  Running setup.py clean for mmcv
Failed to build mmcv
ERROR: Could not build wheels for mmcv, which is required to install pyproject.toml-based projects

```

any suggestions please.

**Comment by fengye1966** [comment]
> i got same error , and i try to install mmcv==2.0.0rc4 I run this command
> 
> `pip install mmcv==2.0.0rc4`
> 
> as well as this
> 
> `mim install mmcv==2.0.0rc4`
> 
> and i get this error for both trying ,
> 
> ```
> 
>      RuntimeError: Error compiling objects for extension
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for mmcv
>   Running setup.py clean for mmcv
> Failed to build mmcv
> ERROR: Could not build wheels for mmcv, which is required to install pyproject.toml-based projects
> ```
> 
> any suggestions please.

you need to set the correct visualizer as mentioned in this link
https://github.com/open-mmlab/mmengine/blob/eb2dc671e99280a86df3c2e2417877b2418240de/docs/en/common_usage/visualize_training_log.md

**Comment by bobo0810** [comment]
The same problem occurs in the following version

mmcv==2.0.0rc4
mmengine==0.7.3
mmpretrain==1.0.0rc8

**Comment by bobo0810** [comment]
> The same problem occurs in the following version
> 
> mmcv==2.0.0rc4 mmengine==0.7.3 mmpretrain==1.0.0rc8

The problem has been solved
python package installation：`mim install mmpretrain==1.0.0rc7`  
or
Source code installation ： `mim install -e .`

**Comment by lemonxiaohei** [comment]
Traceback (most recent call last):
  File "\mmpretrain\tools\train.py", line 166, in <module>
    main()
  File "\mmpretrain\tools\train.py", line 155, in main
    runner = Runner.from_cfg(cfg)
  File "C:\ProgramData\anaconda3\lib\site-packages\mmengine\runner\runner.py", line 445, in from_cfg
    runner = cls(
  File "C:\ProgramData\anaconda3\lib\site-packages\mmengine\runner\runner.py", line 399, in __init__
    self.visualizer = self.build_visualizer(visualizer)
  File "C:\ProgramData\anaconda3\lib\site-packages\mmengine\runner\runner.py", line 786, in build_visualizer
    return VISUALIZERS.build(visualizer)
  File "C:\ProgramData\anaconda3\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\ProgramData\anaconda3\lib\site-packages\mmengine\registry\build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'UniversalVisualizer is not in the mmengine::visualizer registry. Please check whether the value of `UniversalVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

![image](https://github.com/open-mmlab/mmpretrain/assets/93571900/b3436cfe-5002-4d90-ad43-3fb118c8f9d4)

**Comment by betterzhou** [comment]
I fixed the error by installing the required package, e.g., mmcv.

**Comment by qsd-github** [comment]
I also encountered this problem. I downloaded the corresponding source code from GitHub directly, and my solution was to use pip to install the library, which solved the registration problem.

**Comment by liuwake** [comment]
I installed mmpretrain by `mim install -q mmengine==0.10.2 mmpretrain`. But I got this `UniversalVisualizer `bug.
I fixed it with `mim install mmacv==2.1.0`.

**Comment by WenLinLliu** [comment]
mmcls                    1.0.0rc6
mmcv                     2.1.0
mmdet                    3.3.0
mmengine                 0.10.4
mmpretrain               1.2.0    
is correct
