### ISSUE TITLE
[Bug] How can I deploy mmpretrain dist_train.sh on kubernete clusters for distributed training

### ISSUE THREAD

**Issue by ThomaswellY** [open-mmlab/mmpretrain#1610]
### Branch

mmcls-1.x branch (v1.0.0rc6 or other 1.x version)

### Describe the bug

Hi , i have been using mmclassification and mmpose smoothly and successfully, and distributed training with multi-gpus on single node is easy with dist_train.sh.
But in my case, i have two nodes on kubernetes cluster. I wonder is there anyway i can apply training script on my kubernets cluster for multi-node-multi-gpu training.
I have successfully applied [https://github.com/microsoft/DeepSpeedExamples/](url) with mpi-operator for distributed training.
Since mmpretrain use torch.distribute.launch to start distributed training, which is not supported by mpi-operator, and most likely be supported by pytorch-operator, I did several tests on pytorch-operator and still be struggling with BUGS.
So i wonder, is there any method to achieved distributed training on kubernete cluster? the methods from ["https://github.com/kubeflow/training-operator/"](url) would be better for me. 
Thank you in advance ~

### Environment

kubernetes clusters

**Comment by ThomaswellY** [comment]
I have done somework, **the main idea is to achieve dist train** ( in this case: **two node with one gpu/per node**) on k8s like  what dist_train.sh did below:
one baremetal server (node-A)
python -m torch.distributed.launch --nproc_per_node=1 --master_port=$PORT --master_addr=$ADDR train.py --config /config.py --work-dir /workdir --launcher pytorch
another baremetal server (node-B)
python -m torch.distributed.launch --nproc_per_node=1 --master_port=$PORT --master_addr=$ADDR train.py --config /config.py --work-dir /workdir --launcher pytorch
process is not going well. I'll paste my configs and logs here:
configs:
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='ResNet',
        depth=101,
        num_stages=4,
        out_indices=(3, ),
        style='pytorch'),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=1000,
        in_channels=2048,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1, 5)))
dataset_type = 'ImageNet'
data_preprocessor = dict(
    num_classes=1000,
    mean=[123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375],
    to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomResizedCrop', scale=224, backend='pillow'),
    dict(type='RandomFlip', prob=0.5, direction='horizontal'),
    dict(type='PackClsInputs')
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='ResizeEdge', scale=256, edge='short', backend='pillow'),
    dict(type='CenterCrop', crop_size=224),
    dict(type='PackClsInputs')
]
train_dataloader = dict(
    pin_memory=True,
    persistent_workers=True,
    collate_fn=dict(type='default_collate'),
    batch_size=32,
    num_workers=5,
    dataset=dict(
        type='ImageNet',
        data_root='/mmclassification/data',
        ann_file='/mmclassification/data/meta/train.txt',
        data_prefix='train',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='RandomResizedCrop', scale=224, backend='pillow'),
            dict(type='RandomFlip', prob=0.5, direction='horizontal'),
            dict(type='PackClsInputs')
        ]),
    sampler=dict(type='DefaultSampler', shuffle=True))
val_dataloader = dict(
    pin_memory=True,
    persistent_workers=True,
    collate_fn=dict(type='default_collate'),
    batch_size=32,
    num_workers=5,
    dataset=dict(
        type='ImageNet',
        data_root='/mmclassification/data',
        ann_file='/mmclassification/data/meta/val.txt',
        data_prefix='val',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='ResizeEdge', scale=256, edge='short', backend='pillow'),
            dict(type='CenterCrop', crop_size=224),
            dict(type='PackClsInputs')
        ]),
    sampler=dict(type='DefaultSampler', shuffle=False))
val_evaluator = dict(type='SingleLabelMetric')
test_dataloader = dict(
    pin_memory=True,
    persistent_workers=True,
    collate_fn=dict(type='default_collate'),
    batch_size=32,
    num_workers=5,
    dataset=dict(
        type='ImageNet',
        data_root='/mmclassification/data',
        ann_file='/mmclassification/data/meta/val.txt',
        data_prefix='val',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='ResizeEdge', scale=256, edge='short', backend='pillow'),
            dict(type='CenterCrop', crop_size=224),
            dict(type='PackClsInputs')
        ]),
    sampler=dict(type='DefaultSampler', shuffle=False))
test_evaluator = dict(type='SingleLabelMetric')
optim_wrapper = dict(
    optimizer=dict(type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0001))
param_scheduler = dict(
    type='MultiStepLR', by_epoch=True, milestones=[30, 60, 90], gamma=0.1)
train_cfg = dict(by_epoch=True, max_epochs=2, val_interval=1)
val_cfg = dict()
test_cfg = dict()
auto_scale_lr = dict(base_batch_size=128)
default_scope = 'mmcls'
default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=40),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(type='CheckpointHook', interval=2, **create_symlink=False**),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='VisualizationHook', enable=True))
env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    type='ClsVisualizer', vis_backends=[dict(type='LocalVisBackend')])
log_level = 'INFO'
load_from = '/mmclassification/pretrain_model/resnet101_8xb32_in1k_20210831-539c63f8.pth'
resume = False
randomness = dict(seed=None, deterministic=False)
launcher = 'pytorch'
work_dir = '/mmclassification/work-dir'
logs on node-A:
06/09 14:23:19 - mmengine - INFO - Epoch(train) [1][ 40/166]  lr: 1.0000e-01  eta: 0:17:21  time: 3.4035  data_time: 0.0013  memory: 4644  loss: 1.5672
06/09 14:25:34 - mmengine - INFO - Epoch(train) [1][ 80/166]  lr: 1.0000e-01  eta: 0:14:34  time: 3.3712  data_time: 0.0062  memory: 4644  loss: 1.3725
06/09 14:27:48 - mmengine - INFO - Epoch(train) [1][120/166]  lr: 1.0000e-01  eta: 0:12:07  time: 3.3815  data_time: 0.0011  memory: 4644  loss: 1.3738
06/09 14:30:02 - mmengine - INFO - Epoch(train) [1][160/166]  lr: 1.0000e-01  eta: 0:09:46  time: 3.2823  data_time: 0.0015  memory: 4644  loss: 1.3642
06/09 14:30:21 - mmengine - INFO - Exp name: resnet101_8xb32_in1k_20230609_142042
06/09 14:30:33 - mmengine - INFO - Epoch(val) [1][40/48]    eta: 0:00:02  time: 0.2402  data_time: 0.0006  memory: 4644  

mmcls-master-0:1:64 [0] include/socket.h:423 NCCL WARN Net : Connection closed by remote peer 10.233.73.34<54596>
mmcls-master-0:1:64 [0] NCCL INFO transport/net_socket.cc:414 -> 2
mmcls-master-0:1:64 [0] NCCL INFO include/net.h:28 -> 2
mmcls-master-0:1:64 [0] NCCL INFO transport/net.cc:459 -> 2
mmcls-master-0:1:64 [0] NCCL INFO proxy.cc:351 -> 2
mmcls-master-0:1:64 [0] NCCL INFO proxy.cc:452 -> 2 [Proxy Thread]
logs on node-B:
Loads checkpoint by local backend from path: /mmclassification/pretrain_model/resnet101_8xb32_in1k_20210831-539c63f8.pth
Traceback (most recent call last):
  File "/mmclassification/tools/train.py", line 166, in <module>
    main()
  File "/mmclassification/tools/train.py", line 162, in main
    runner.train()
  File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/runner.py", line 1701, in train
    model = self.train_loop.run()  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/loops.py", line 102, in run
    self.runner.val_loop.run()
  File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/loops.py", line 366, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/usr/local/lib/python3.8/dist-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/evaluator/metric.py", line 110, in evaluate
    results = collect_results(self.results, size, self.collect_device)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/dist/dist.py", line 927, in collect_results
    return collect_results_cpu(results, size, tmpdir)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/dist/dist.py", line 986, in collect_results_cpu
    with open(osp.join(tmpdir, f'part_{rank}.pkl'), 'wb') as f:  # type: ignore
FileNotFoundError: [Errno 2] **No such file or directory: '.dist_test/tmpai3d4bbh/part_1.pkl'** 
 I had modified checkpoint=dict(type='CheckpointHook', interval=2, **create_symlink=False**)
But it doesn't work
Any suggestion to complete it ? I'd like to pull request after resolving this issue.
