### ISSUE TITLE
[Bug] Fail to use in1k

### ISSUE THREAD

**Issue by wwsyan** [open-mmlab/mmpretrain#1619]
### Branch

mmcls-1.x branch (v1.0.0rc6 or other 1.x version)

### Describe the bug

Encountered errors when I try [How to visualize the transformed images](https://mmpretrain.readthedocs.io/en/latest/useful_tools/dataset_visualization.html#how-to-visualize-the-transformed-images).
```shell
!python ../mmpretrain/tools/visualization/browse_dataset.py ../mmpretrain/configs/resnet/resnet50_8xb32_in1k.py -n 20
```
I got:
```shell
Traceback (most recent call last):
  File "[d:\Anaconda\envs\openmmlab_py3.8\lib\site-packages\mmengine\registry\build_functions.py](file:///D:/Anaconda/envs/openmmlab_py3.8/lib/site-packages/mmengine/registry/build_functions.py)", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "[f:\mmpretrain\mmpretrain\mmpretrain\datasets\imagenet.py](file:///F:/mmpretrain/mmpretrain/mmpretrain/datasets/imagenet.py)", line 39, in __init__
    super().__init__(
  File "[f:\mmpretrain\mmpretrain\mmpretrain\datasets\custom.py](file:///F:/mmpretrain/mmpretrain/mmpretrain/datasets/custom.py)", line 219, in __init__
    self.full_init()
  File "[f:\mmpretrain\mmpretrain\mmpretrain\datasets\base_dataset.py](file:///F:/mmpretrain/mmpretrain/mmpretrain/datasets/base_dataset.py)", line 178, in full_init
    super().full_init()
  File "[d:\Anaconda\envs\openmmlab_py3.8\lib\site-packages\mmengine\dataset\base_dataset.py](file:///D:/Anaconda/envs/openmmlab_py3.8/lib/site-packages/mmengine/dataset/base_dataset.py)", line 296, in full_init
    self.data_list = self.load_data_list()
  File "[f:\mmpretrain\mmpretrain\mmpretrain\datasets\custom.py](file:///F:/mmpretrain/mmpretrain/mmpretrain/datasets/custom.py)", line 266, in load_data_list
    lines = list_from_file(self.ann_file)
  File "[d:\Anaconda\envs\openmmlab_py3.8\lib\site-packages\mmengine\fileio\parse.py](file:///D:/Anaconda/envs/openmmlab_py3.8/lib/site-packages/mmengine/fileio/parse.py)", line 60, in list_from_file
    text = get_text(filename, encoding, backend_args=backend_args)
  File "[d:\Anaconda\envs\openmmlab_py3.8\lib\site-packages\mmengine\fileio\io.py](file:///D:/Anaconda/envs/openmmlab_py3.8/lib/site-packages/mmengine/fileio/io.py)", line 208, in get_text
    return backend.get_text(filepath, encoding)
  File "[d:\Anaconda\envs\openmmlab_py3.8\lib\site-packages\mmengine\fileio\backends\local_backend.py](file:///D:/Anaconda/envs/openmmlab_py3.8/lib/site-packages/mmengine/fileio/backends/local_backend.py)", line 56, in get_text
    with open(filepath, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/imagenet\\meta/train.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".[./mmpretrain/tools/visualization/browse_dataset.py](https://file+.vscode-resource.vscode-cdn.net/f%3A/MMPretrain/view_dataset_images/mmpretrain/tools/visualization/browse_dataset.py)", line 253, in <module>
...
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "[d:\Anaconda\envs\openmmlab_py3.8\lib\site-packages\mmengine\registry\build_functions.py](file:///D:/Anaconda/envs/openmmlab_py3.8/lib/site-packages/mmengine/registry/build_functions.py)", line 144, in build_from_cfg
    raise type(e)(
FileNotFoundError: class `ImageNet` in mmpretrain/datasets/imagenet.py: [Errno 2] No such file or directory: 'data/imagenet\\meta/train.txt'
```

### Environment

```python
{'sys.platform': 'win32',
 'Python': '3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit '
           '(AMD64)]',
 'CUDA available': True,
 'numpy_random_seed': 2147483648,
 'GPU 0': 'NVIDIA GeForce GTX 1650',
 'CUDA_HOME': '[C:/Program](file:///C:/Program) Files/NVIDIA GPU Computing Toolkit/CUDA\\v11.6',
 'NVCC': 'Not Available',
 'MSVC': '用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.36.32532 版',
 'GCC': 'n/a',
 'PyTorch': '2.0.1',
 'TorchVision': '0.15.2',
 'OpenCV': '4.7.0',
 'MMEngine': '0.7.4',
 'MMCV': '2.0.0',
 'MMPreTrain': '1.0.0rc8+unknown'}
```

### Other information
cifar10 and cifar100 are ok.
The exact same error occurs when I attempt to use ImageNet, like:
```powershell
!python ../mmpretrain/tools/train.py ../mmpretrain/configs/resnet/resnet18_8xb32_in1k.py
```

**Comment by Ezra-Yu** [comment]
Do you use the sub-folder format ImageNet dataset?

**Comment by wwsyan** [comment]
> Do you use the sub-folder format ImageNet dataset?
> 
> remove the `ann_file="meta/train.txt"` in `train_dataloader.dataset`.

No, the running directory of the command line is completely empty.

**Comment by Ezra-Yu** [comment]
so, what's your imagenet dataset struct?

**Comment by wwsyan** [comment]
> so, what's your imagenet dataset struct?

I'm a bit confused. Do I need to prepare the ImageNet data myself? I thought it would be automatically downloaded like when using CIFAR-10 and CIFAR-100.

**Comment by Ezra-Yu** [comment]
> I'm a bit confused. Do I need to prepare the ImageNet data myself? 

Yes. It is so big that we do not support automatic downloads.

**Comment by wwsyan** [comment]
> Yes. It is so big that we do not support automatic downloads.
Thx! I have no more questions. ^_^
