### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sun254667307** [open-mmlab/mmpretrain#1701]
### Branch

main branch (mmpretrain version)

### Describe the bug

We encounter this issue when running MiniGPT4

Traceback (most recent call last):
  File "/home/aaa/envs/mmpretrain/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/mnt/workspace/workgroup/mmpretrain/mmpretrain/models/multimodal/minigpt4/minigpt4.py", line 81, in __init__
    load_checkpoint(self.vision_encoder, vision_encoder_weight)
  File "/home/aaa/envs/mmpretrain/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 642, in load_checkpoint
    return _load_checkpoint_to_model(model, checkpoint, strict, logger,
  File "/home/aaa/envs/mmpretrain/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 607, in _load_checkpoint_to_model
    load_state_dict(model, state_dict, strict, logger)
  File "/home/aaa/envs/mmpretrain/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 116, in load_state_dict
    load(module, state_dict)
  File "/home/aaa/envs/mmpretrain/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 92, in load
    module._load_from_state_dict(local_state_dict, prefix, local_metadata,
  File "/home/aaa/envs/mmpretrain/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1474, in _load_from_state_dict
    hook(state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
  File "/mnt/workspace/workgroup/mmpretrain/mmpretrain/models/backbones/vision_transformer.py", line 397, in _prepare_pos_embed
    if (not self.with_cls_token
  File "/home/aaa/envs/mmpretrain/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BEiTViT' object has no attribute 'with_cls_token'

### Environment

mmcv==2.0.1
mmcv-full==1.7.0
mmengine==0.8.0
mmpretrain==1.0.0
torch==1.12.1+cu113

### Other information

![image](https://github.com/open-mmlab/mmpretrain/assets/10826283/f11386d7-cd7f-4cd9-8c40-a3f6d5f47a53)

this issue can be solved in the above way

**Comment by fangyixiao18** [comment]
Fixed in https://github.com/open-mmlab/mmpretrain/pull/1705, please use dev branch with newest code
