### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by RomanticGodVAN** [open-mmlab/mmpretrain#1740]
### Branch

main branch (mmpretrain version)

### Describe the bug

Traceback (most recent call last):
  File "C:\Users\31316\Desktop\evolution\mmpretrain\demo\image_demo.py", line 7, in <module>
    from mmpretrain.apis import ImageClassificationInferencer
  File "c:\users\31316\desktop\evolution\mmpretrain\mmpretrain\__init__.py", line 2, in <module>
    import mmcv
  File "D:\anaconda\envs\openmmlab\lib\site-packages\mmcv\__init__.py", line 4, in <module>
    from .image import *
  File "D:\anaconda\envs\openmmlab\lib\site-packages\mmcv\image\__init__.py", line 11, in <module>
    from .photometric import (adjust_brightness, adjust_color, adjust_contrast,
  File "D:\anaconda\envs\openmmlab\lib\site-packages\mmcv\image\photometric.py", line 8, in <module>
    from PIL import Image, ImageEnhance
  File "D:\anaconda\envs\openmmlab\lib\site-packages\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: 找不到指定的模块。

### Environment

Traceback (most recent call last):
  File "C:\Users\31316\Desktop\evolution\mmpretrain\demo\image_demo.py", line 7, in <module>
    from mmpretrain.apis import ImageClassificationInferencer
  File "c:\users\31316\desktop\evolution\mmpretrain\mmpretrain\__init__.py", line 2, in <module>
    import mmcv
  File "D:\anaconda\envs\openmmlab\lib\site-packages\mmcv\__init__.py", line 4, in <module>
    from .image import *
  File "D:\anaconda\envs\openmmlab\lib\site-packages\mmcv\image\__init__.py", line 11, in <module>
    from .photometric import (adjust_brightness, adjust_color, adjust_contrast,
  File "D:\anaconda\envs\openmmlab\lib\site-packages\mmcv\image\photometric.py", line 8, in <module>
    from PIL import Image, ImageEnhance
  File "D:\anaconda\envs\openmmlab\lib\site-packages\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: 找不到指定的模块。

### Other information

Traceback (most recent call last):
  File "C:\Users\31316\Desktop\evolution\mmpretrain\demo\image_demo.py", line 7, in <module>
    from mmpretrain.apis import ImageClassificationInferencer
  File "c:\users\31316\desktop\evolution\mmpretrain\mmpretrain\__init__.py", line 2, in <module>
    import mmcv
  File "D:\anaconda\envs\openmmlab\lib\site-packages\mmcv\__init__.py", line 4, in <module>
    from .image import *
  File "D:\anaconda\envs\openmmlab\lib\site-packages\mmcv\image\__init__.py", line 11, in <module>
    from .photometric import (adjust_brightness, adjust_color, adjust_contrast,
  File "D:\anaconda\envs\openmmlab\lib\site-packages\mmcv\image\photometric.py", line 8, in <module>
    from PIL import Image, ImageEnhance
  File "D:\anaconda\envs\openmmlab\lib\site-packages\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: 找不到指定的模块。

**Comment by Ezra-Yu** [comment]
try:
```
pip install Pillow
```
