### ISSUE TITLE
"some parameters appear in more than one parameter group" caused by the custom_keys configuration in paramwise_cfg (This issue has not occurred in mmclassification)

### ISSUE THREAD

**Issue by cilinyan** [open-mmlab/mmpretrain#1819]
### Branch

main branch (mmpretrain version)

### Describe the bug

When I set the custom_keys in the paramwise_cfg, PyTorch throws an error "some parameters appear in more than one parameter group." However, this issue did not occur in the old version of `mmcls`, and I wonder if I have misconfigured the configuration file or if there is some other problem.

**Config File:** 
```python
# optimizer
optimizer     = dict(type='AdamW', lr=1.3e-4, weight_decay=0.04)
paramwise_cfg = dict(
    # layer_decay_rate = 0.75, # layer-wise lr decay factor
    norm_decay_mult  = 0.0,
    bias_decay_mult  = 0.0,
    custom_keys      = {
        '.absolute_pos_embed'          : dict(decay_mult=0.0),
        '.relative_position_bias_table': dict(decay_mult=0.0),
        '.cls_token'                   : dict(decay_mult=0.0),
        'vision_backbone'              : dict(lr_mult=0, decay_mult=0),
    }
)
optim_wrapper = dict(
    type                = 'OptimWrapper',
    optimizer           = optimizer,
    accumulative_counts = 4,
    paramwise_cfg       = paramwise_cfg
)
```

**Error:**
```shell 
Traceback (most recent call last):
  File "tools/train.py", line 166, in <module>
    main()
  File "tools/train.py", line 162, in main
    runner.train()
  File "/data/clyan/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1733, in train
    self.optim_wrapper = self.build_optim_wrapper(self.optim_wrapper)
  File "/data/clyan/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1114, in build_optim_wrapper
    return build_optim_wrapper(self.model, optim_wrapper)
  File "/data/clyan/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmengine/optim/optimizer/builder.py", line 208, in build_optim_wrapper
    optim_wrapper = optim_wrapper_constructor(model)
  File "/data/clyan/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmengine/optim/optimizer/default_constructor.py", line 315, in __call__
    optimizer = OPTIMIZERS.build(optimizer_cfg)
  File "/data/clyan/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/data/clyan/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/data/clyan/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/optim/adamw.py", line 74, in __init__
    super(AdamW, self).__init__(params, defaults)
  File "/data/clyan/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/optim/optimizer.py", line 54, in __init__
    self.add_param_group(param_group)
  File "/data/clyan/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/optim/optimizer.py", line 278, in add_param_group
    raise ValueError("some parameters appear in more than one parameter group")
ValueError: some parameters appear in more than one parameter group
```

### Environment

```python
{'sys.platform': 'linux',
 'Python': '3.8.18 | packaged by conda-forge | (default, Oct 10 2023, '
           '15:44:36) [GCC 12.3.0]',
 'CUDA available': True,
 'numpy_random_seed': 2147483648,
 'GPU 0,1,2,3,4,5,6,7': 'A100-SXM4-40GB',
 'CUDA_HOME': '/usr/local/cuda',
 'NVCC': 'Cuda compilation tools, release 11.1, V11.1.74',
 'GCC': 'gcc (GCC) 9.3.0',
 'PyTorch': '1.10.1',
 'TorchVision': '0.11.2',
 'OpenCV': '4.8.1',
 'MMEngine': '0.9.0',
 'MMCV': '2.0.1',
 'MMPreTrain': '1.0.2+'}
```

**Comment by cilinyan** [comment]
Done

**Comment by cilinyan** [comment]
Done
