### ISSUE TITLE
[Bug] ImageClassificationInferencer may be initialized incorrectly in non-'mmpretrain' scope.

### ISSUE THREAD

**Issue by ZhangYouyi** [open-mmlab/mmpretrain#1839]
### Branch

main branch (mmpretrain version)

### Describe the bug

If the default scope is set to be non-'mmpretrain', ImageClassificationInferencer may be initialized incorrectly.

**Check:**

The following script can run correctly.

```python
from mmengine import Config, init_default_scope
from mmpretrain.models import ImageClassifier

from fer_zoo.registry import MODELS

cfg = Config.fromfile('configs/img_cls/cbam-resnet50.py')
init_default_scope('pkgxxx')
model: ImageClassifier = MODELS.build(cfg['model'])
print(model)
```

**Reproduction:**

Run the following python script:

```python
from mmengine import init_default_scope
from mmpretrain.apis import ImageClassificationInferencer

init_default_scope('pkgxxx')
model = 'configs/img_cls/cbam-resnet50.py'
inferencer = ImageClassificationInferencer(model, pretrained=False)
print(inferencer)
```

Then the following error msg and full calling stack are:

```
Traceback (most recent call last):
  File "/home/zhangyouyi/experiment/demo/tmp.py", line 6, in <module>
    inferencer = ImageClassificationInferencer(model, pretrained=False)
  File "/home/zhangyouyi/miniconda3/envs/mmpt_test/lib/python3.10/site-packages/mmpretrain/apis/image_classification.py", line 66, in __init__
    super().__init__(
  File "/home/zhangyouyi/miniconda3/envs/mmpt_test/lib/python3.10/site-packages/mmpretrain/apis/base.py", line 109, in __init__
    model = get_model(
  File "/home/zhangyouyi/miniconda3/envs/mmpt_test/lib/python3.10/site-packages/mmpretrain/apis/model.py", line 192, in get_model
    model = MODELS.build(config.model)
  File "/home/zhangyouyi/miniconda3/envs/mmpt_test/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/zhangyouyi/miniconda3/envs/mmpt_test/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/zhangyouyi/miniconda3/envs/mmpt_test/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/zhangyouyi/miniconda3/envs/mmpt_test/lib/python3.10/site-packages/mmpretrain/models/classifiers/image.py", line 71, in __init__
    backbone = MODELS.build(backbone)
  File "/home/zhangyouyi/miniconda3/envs/mmpt_test/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/zhangyouyi/miniconda3/envs/mmpt_test/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/zhangyouyi/miniconda3/envs/mmpt_test/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'cbam_resnet50 is not in the mmpretrain::model registry. Please check whether the value of `cbam_resnet50` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
```

### Environment

{'sys.platform': 'linux',
 'Python': '3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]',
 'CUDA available': True,
 'numpy_random_seed': 2147483648,
 'GPU 0': 'NVIDIA GeForce GTX 1650 Ti',
 'CUDA_HOME': None,
 'GCC': 'gcc (Uos 8.3.0.3-3+rebuild) 8.3.0',
 'PyTorch': '2.0.0+cu117',
 'TorchVision': '0.15.0+cu117',
 'OpenCV': '4.5.5',
 'MMEngine': '0.9.0',
 'MMCV': '2.0.0',
 'MMPreTrain': '1.1.0+14749b2'}

**Comment by Taited** [comment]
You need to register all modules mannully by:
```python
from mmpretrain.utils import register_all_modules

register_all_modules()
```
