### ISSUE TITLE
[Bug] TypeError: __init__() got an unexpected keyword argument 'init_cfg'

### ISSUE THREAD

**Issue by Carina02** [open-mmlab/mmpretrain#1878]
### Branch

main branch (mmpretrain version)

### Describe the bug

I was trying to implement a customized backbone network which is an encoder of MAE (https://github.com/NASA-IMPACT/hls-foundation-os). 
(Later I have also tried to train with the default Lenet5_mnist.py and it gives exact the same error )

By adding the following:

```
init_cfg=dict(
            type='Pretrained',
            checkpoint='https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_8xb32_in1k_20210831-ea4938fc.pth',
            prefix='backbone',
        )
```
it gives the error message:

```
Traceback (most recent call last):
  File "tools/train.py", line 164, in <module>
    main()
  File "tools/train.py", line 152, in main
    runner = Runner.from_cfg(cfg)
  File "D:\Python38\lib\site-packages\mmengine\runner\runner.py", line 462, in from_cfg
    runner = cls(
  File "D:\Python38\lib\site-packages\mmengine\runner\runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "D:\Python38\lib\site-packages\mmengine\runner\runner.py", line 837, in build_model
    model = MODELS.build(model)
  File "D:\Python38\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\Python38\lib\site-packages\mmengine\registry\build_functions.py", line 233, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\Python38\lib\site-packages\mmengine\registry\build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "c:\users\10208\desktop\mmpretrain\mmpretrain\models\classifiers\image.py", line 71, in __init__
    backbone = MODELS.build(backbone)
  File "D:\Python38\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\Python38\lib\site-packages\mmengine\registry\build_functions.py", line 233, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\Python38\lib\site-packages\mmengine\registry\build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'init_cfg'

```
Without the init_cfg key it works. Any ideas would be helpful

### Environment

Package         Version    Source
--------------  ---------  --------------------------------------------
mmcv            2.1.0      https://github.com/open-mmlab/mmcv
mmengine        0.10.3     https://github.com/open-mmlab/mmengine
mmpretrain      1.2.0      \mmpretrain
mmsegmentation  1.2.2      https://github.com/open-mmlab/mmsegmentation

**Comment by Carina02** [comment]
solved
