### ISSUE TITLE
RuntimeError: The configuration file type in the inheritance chain must match the current configuration file type, either "lazy_import" or non-"lazy_import".  

### ISSUE THREAD

**Issue by santoshamd** [open-mmlab/mmpretrain#1898]
### Branch

main branch (mmpretrain version)

### Describe the bug

I am following https://mmpretrain.readthedocs.io/en/dev/papers/replknet.html

```
import torch
from mmpretrain import get_model

model = get_model('replknet-31B_3rdparty_in1k', pretrained=True)
inputs = torch.rand(1, 3, 224, 224)
out = model(inputs)
print(type(out))
# To extract features.
feats = model.extract_feat(inputs)
print(type(feats))
```
running this code is giving this error

Traceback (most recent call last):
  File "C:\Users\robert\"\ml_solution\vit\replknet.py.py", line 4, in <module>
    model = get_model('replknet-31B_3rdparty_in1k')
  File "c:\users\robert\"\ml_solution\vit\mmpretrain\mmpretrain\apis\model.py", line 169, in get_model
    metainfo = ModelHub.get(model)
  File "c:\users\robert\"\ml_solution\vit\mmpretrain\mmpretrain\apis\model.py", line 64, in get
    metainfo.config = Config.fromfile(metainfo.config)
  File "C:\Users\robert\AppData\Local\anaconda3\envs\vit\lib\site-packages\mmengine\config\config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "C:\Users\robert\AppData\Local\anaconda3\envs\vit\lib\site-packages\mmengine\config\config.py", line 947, in _file2dict
    raise e
  File "C:\Users\robert\AppData\Local\anaconda3\envs\vit\lib\site-packages\mmengine\config\config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "C:\Users\robert\AppData\Local\anaconda3\envs\vit\lib\site-packages\mmengine\config\config.py", line 846, in _file2dict
    raise RuntimeError(
RuntimeError: The configuration file type in the inheritance chain must match the current configuration file type, either "lazy_import" or non-"lazy_import". You got this error since you use the syntax like `with read_base(): ...` or import non-builtin module in c:\users\robert\mmpretrain\.mim\configs\replknet\../_base_/models/replknet-31B_in1k.py. See more information in https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html

### Environment

{'sys.platform': 'win32',
 'Python': '3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, '
           '19:44:50) [MSC v.1916 64 bit (AMD64)]',
 'CUDA available': False,
 'MUSA available': False,
 'numpy_random_seed': 2147483648,
 'GCC': 'n/a',
 'PyTorch': '2.3.0+cpu',
 'TorchVision': '0.18.0+cpu',
 'OpenCV': '4.9.0',
 'MMEngine': '0.10.4',
 'MMCV': '2.2.0',
 'MMPreTrain': '1.2.0+'}

**Comment by RameshOswal** [comment]
Following this

**Comment by wangqiang9** [comment]
I have the same promblem.

**Comment by sxbkdby8** [comment]
I have the same promblem.

**Comment by anxingle** [comment]
Following this

**Comment by wangyao0512** [comment]
这个原因在于 config里的差异，比如 原本的config schedule_2x.py是这样的，不满足lazy_config

<img width="944" height="602" alt="Image" src="https://github.com/user-attachments/assets/4cb3d451-7c01-42e5-bceb-52812106dc31" />
 把它改成就work,直接写成key的这种形式

<img width="1040" height="622" alt="Image" src="https://github.com/user-attachments/assets/92569daf-5590-4e83-a1ac-b22b205db811" />
